site_name: Cs Core

theme:
  name: material
  palette:
    scheme: slate

plugins:
  - search
  - include-markdown

nav:
  - Home: index.md
  - Linux:
      - Files & IO: linux/files/index.md
      - Overview of Fundamentals: linux/overview.md
      - Devices: linux/devices/index.md
      - Userspace: linux/userspace/userspace.md
  - Containers:
      - Overview: containers/overview.md
  - C Programming:
      - UB (Undefined Behavior): c/ub.md
      - Data Types Indepth: c/data-types.md
