site_name: Cs Core

theme:
  name: material
  palette:
    scheme: slate

plugins:
  - search
  - include-markdown

nav:
  - Home: index.md
  - German:
      - Home: German/index.md
  - Kubernetes:
      - Roadmap: kubernetes/index.md
      - Volumes: kubernetes/volumes.md
      - Containers: linux/containers/index.md
      - Authentication: kubernetes/authentication.md
      
  - Linux:
      - Files & IO: linux/files/index.md
      - Overview of Fundamentals: linux/overview.md
      - Devices: linux/devices/index.md
      - Userspace: linux/userspace/index.md
      - Boot Process: linux/boot-process.md
      - Vim: linux/vim.md
      - Storage: linux/storage.md 
      
  - Cpu:
      - CPU & Memory: cpu/memory.md
  - Containers:
      - Overview: containers/overview.md
  - C Programming:
      - UB (Undefined Behavior): c/ub.md
      - Data Types Indepth: c/data-types.md
  - Operating Systems:
      - Processes: os/virtualizing-processes.md 
      - Virtualizing memory: os/virtualizing-memory.md   
      - Scheduling: os/scheduling.md 
      - Concurrency: os/concurrency.md
  - How stuff works:
      - How keyboards work: walkthroughs/how-keyboards-work.md
      - How network requests are made: walkthroughs/how-network-calls-work.md
      - How DB Connection Works: walkthroughs/how-db-connection-works.md
      